import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const serverSource = await readFile(new URL("../server.js", import.meta.url), "utf8");
const readerSource = await readFile(new URL("../scripts/read-otchlan-position.ps1", import.meta.url), "utf8");
const nativeReaderSource = await readFile(new URL("../src/OtchlanMemoryReader/Program.cs", import.meta.url), "utf8");

test("server publishes Otchlan position from process memory", () => {
  assert.match(serverSource, /const OTCHLAN_POSITION_READER = path\.join\(__dirname, "scripts", "read-otchlan-position\.ps1"\);/);
  assert.match(serverSource, /const OTCHLAN_RELEASE_POSITION_READER = path\.join\(__dirname, "bin", "OtchlanMemoryReader\.exe"\);/);
  assert.match(serverSource, /const OTCHLAN_DEV_POSITION_READER = path\.join\(__dirname, "src", "OtchlanMemoryReader"/);
  assert.match(serverSource, /const OTCHLAN_POSITION_POLL_MS = Number\(process\.env\.OTCHLAN_POSITION_POLL_MS \|\| 100\);/);
  assert.match(serverSource, /const OTCHLAN_MOB_POLL_MS = Number\(process\.env\.OTCHLAN_MOB_POLL_MS \|\| 1000\);/);
  assert.match(serverSource, /startGamePositionReader\(gameProcess\.pid\);/);
  assert.match(serverSource, /sendEvent\(client, "game-position", lastGamePosition\);/);
  assert.match(serverSource, /broadcast\("game-position", lastGamePosition\);/);
  assert.match(serverSource, /const readerKind = nativeReaderAvailable \? "native-dotnet" : "powershell";/);
  assert.match(serverSource, /"-MobPollMs",/);
  assert.match(serverSource, /event: "game-position-memory"/);
  assert.match(serverSource, /source: "process-memory"/);
  assert.match(serverSource, /const hasVitals = payload\.vitals && typeof payload\.vitals === "object"/);
  assert.match(serverSource, /const hasEnvironment = payload\.environment && typeof payload\.environment === "object"/);
  assert.match(serverSource, /vitals: hasVitals \? normalizeGameVitals\(payload\.vitals\) : previousPosition\.vitals/);
  assert.match(serverSource, /economy: hasEconomy \? normalizeGameEconomy\(payload\.economy\) : previousPosition\.economy/);
  assert.match(serverSource, /time: hasTime \? normalizeGameTime\(payload\.time\) : previousPosition\.time/);
  assert.match(serverSource, /environment: hasEnvironment \? normalizeGameEnvironment\(payload\.environment\) : previousPosition\.environment/);
  assert.match(serverSource, /effects: hasEffects \? normalizeGameEffects\(payload\.effects\) : previousPosition\.effects/);
  assert.match(serverSource, /conditions: hasConditions \? normalizeGameConditions\(payload\.conditions\) : previousPosition\.conditions/);
  assert.match(serverSource, /mobs: hasMobs \? normalizeGameMobs\(payload\.mobs\) : previousPosition\.mobs/);
  assert.match(serverSource, /function normalizeGameMobs\(mobs = \[\]\) \{/);
  assert.match(serverSource, /function logGamePositionMemory\(position\) \{/);
  assert.match(serverSource, /const mobs = Array\.isArray\(position\.mobs\) \? position\.mobs : \[\]/);
  assert.match(serverSource, /const mobCount = mobs\.length/);
  assert.match(serverSource, /level: finiteNumber\(economy\.level\)/);
  assert.match(serverSource, /function normalizeGameTime\(time = \{\}\) \{/);
  assert.match(serverSource, /function normalizeGameEnvironment\(environment = \{\}\) \{/);
  assert.match(serverSource, /canObserveMobs: environment\.canObserveMobs !== false/);
});

test("server enriches unnamed memory effects from extracted game symbols", () => {
  assert.match(serverSource, /import \{ createReadStream, existsSync, readFileSync, statSync, watch \} from "node:fs";/);
  assert.match(serverSource, /let worldCacheEffectNames = null;/);
  assert.match(serverSource, /const name = normalizeEffectName\(String\(effect\?\.name \|\| ""\)\) \|\| getWorldCacheEffectName\(number\);/);
  assert.match(serverSource, /function getWorldCacheEffectNames\(\) \{/);
  assert.match(serverSource, /for \(const entry of cache\.skillSymbols \|\| \[\]\)/);
});

test("position reader extracts G1 location and area file offsets", () => {
  assert.match(readerSource, /\$G1_ADDRESS = \[IntPtr\]0x47f570/);
  assert.match(readerSource, /\$MOBS_MOBQ_ADDRESS = \[IntPtr\]0x477da0/);
  assert.match(readerSource, /\$MOBS_MOBY_ADDRESS = \[IntPtr\]0x478610/);
  assert.match(readerSource, /\$MOBS_MOBYWK_ADDRESS = \[IntPtr\]0x481a40/);
  assert.match(readerSource, /\$BUFFER_SIZE = 8192/);
  assert.match(readerSource, /\$MOB_VISIBLE_RANGE = 4/);
  assert.match(readerSource, /\$LOKAC_OFFSET = 312/);
  assert.match(readerSource, /\$PLIKAREA_OFFSET = 1084/);
  assert.match(readerSource, /\$LEVEL_OFFSET = 310/);
  assert.match(readerSource, /\$UMI_OFFSET = 1102/);
  assert.match(readerSource, /\$HP_OFFSET = 202/);
  assert.match(readerSource, /\$MANA_OFFSET = 210/);
  assert.match(readerSource, /\$MV_OFFSET = 218/);
  assert.match(readerSource, /\$EXPE_OFFSET = 226/);
  assert.match(readerSource, /\$CZAS_OFFSET = 1050/);
  assert.match(readerSource, /\$DZIEN_OFFSET = 1056/);
  assert.match(readerSource, /\$LICZG_OFFSET = 234/);
  assert.match(readerSource, /\$LICZS_OFFSET = 238/);
  assert.match(readerSource, /\$LIGHT_OFFSET = 296/);
  assert.match(readerSource, /\$HUNGER_WARNING_THRESHOLD = 3000/);
  assert.match(readerSource, /\$MINEXP_OFFSET = 5062/);
  assert.match(readerSource, /\$EXPLIMIT_OFFSET = 5066/);
  assert.match(readerSource, /\$PRZYSOBIE_OFFSET = 318/);
  assert.match(readerSource, /\$CZARKI_OFFSET = 4462/);
  assert.match(readerSource, /\$CZARKI_SKILL_BASE_NUMER = 152/);
  assert.match(readerSource, /\$MONEY_OBJECT_VALUES = @\{/);
  assert.match(readerSource, /500 = 1/);
  assert.match(readerSource, /1105 = 100/);
  assert.match(readerSource, /495 = 50000/);
  assert.match(readerSource, /ReadProcessMemory/);
  assert.match(readerSource, /ToInt16\(\$buffer, \$LOKAC_OFFSET\)/);
  assert.match(readerSource, /\$level = \[int\]\$buffer\[\$LEVEL_OFFSET\]/);
  assert.match(readerSource, /\$timeRaw = \[int\]\[BitConverter\]::ToUInt16\(\$buffer, \$CZAS_OFFSET\)/);
  assert.match(readerSource, /\$timeHour = \[int\]\(\[Math\]::Floor\(\$timeRaw \/ 180\) % 24\)/);
  assert.match(readerSource, /\$isNight = Test-IsNightHour \$timeHour/);
  assert.match(readerSource, /\$canObserveMobs = \$light -gt 0 -or -not \$isNight/);
  assert.match(readerSource, /\$journeyDay = \[BitConverter\]::ToInt32\(\$buffer, \$DZIEN_OFFSET\)/);
  assert.match(readerSource, /ToDouble\(\$buffer, \$HP_OFFSET\)/);
  assert.match(readerSource, /\$MONEY_OBJECT_VALUES\.ContainsKey\(\$objectNumber\)/);
  assert.match(readerSource, /\$gold \+= \$quantity \* \$MONEY_OBJECT_VALUES\[\$objectNumber\]/);
  assert.match(readerSource, /GetEncoding\(1250\)/);
  assert.match(readerSource, /worldKey = \$worldKey/);
  assert.match(readerSource, /vitals = @\{/);
  assert.match(readerSource, /economy = @\{/);
  assert.match(readerSource, /level = \$level/);
  assert.match(readerSource, /minExp = \$minExp/);
  assert.match(readerSource, /expLimit = \$expLimit/);
  assert.match(readerSource, /time = @\{/);
  assert.match(readerSource, /day = \$journeyDay/);
  assert.match(readerSource, /environment = @\{/);
  assert.match(readerSource, /canObserveMobs = \$canObserveMobs/);
  assert.match(readerSource, /effects = \$effects/);
  assert.match(readerSource, /conditions = \$conditions/);
  assert.match(readerSource, /mobs = \$mobs/);
  assert.match(readerSource, /function Get-MobNamesById/);
  assert.match(readerSource, /function Get-QuestMobNamesById/);
  assert.match(readerSource, /function Get-CurrentMobs/);
  assert.match(readerSource, /\$visibleCardinal4 = \$z -eq \$playerZ -and \$direction -and \$distance -gt 0 -and \$distance -le \$MOB_VISIBLE_RANGE/);
});

test("native memory reader exposes light and mob observability", () => {
  assert.match(nativeReaderSource, /const int LightOffset = 296;/);
  assert.match(nativeReaderSource, /var light = ReadInt32\(buffer, LightOffset\);/);
  assert.match(nativeReaderSource, /var isNight = IsNightHour\(timeHour\);/);
  assert.match(nativeReaderSource, /var canObserveMobs = light > 0 \|\| !isNight;/);
  assert.match(nativeReaderSource, /Environment = new EnvironmentInfo\(light, light > 0, isNight, canObserveMobs\)/);
  assert.match(nativeReaderSource, /conditions\.Add\(new ConditionInfo\("darkness", "ciemność", 0, "state"\)\);/);
  assert.match(nativeReaderSource, /static bool IsNightHour\(int hour\)/);
  assert.match(nativeReaderSource, /record EnvironmentInfo/);
});
